In [2]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "nikhil7280/student-performance-multiple-linear-regression",
  "Student_Performance.csv",
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)
df.head()

d:\Programs\Machine_Learning\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\jewin\AppData\Local\Temp\ipykernel_20132\2084205128.py:4: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to C:\Users\jewin\.cache\kagglehub\datasets\nikhil7280\student-performance-multiple-linear-regression\versions\1\Student_Performance.csv...

100%|██████████| 171k/171k [00:00<00:00, 177kB/s]

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [19]:
X = df.drop(columns=['Extracurricular Activities','Performance Index'])
y = df['Performance Index']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.head()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced
9254,5,49,7,5
1561,2,48,7,6
1670,2,81,7,2
6087,2,46,6,1
6669,8,47,9,0

In [33]:
def predict(X, w, b):
    p = X @ w + b
    return p

def compute_cost(X, y, w, b):
    cost = 0
    m = X.shape[0]
    err = (X @ w +b) - y
    cost = (err ** 2).sum() / (2*m)
    return cost

def compute_gradient(X, y, w, b):
    m, n = X.shape
    dj_dw = np.zeros((n,))
    dj_db = 0
    err = X @ w + b - y
    dj_db = err.sum() / m
    dj_dw = (X.T @ err) / m
    return dj_dw, dj_db

def multipleLinearRegression(X, y, w_in, b_in, alpha, num_iters):
    w = copy.deepcopy(w_in)
    b = b_in
    for i in range(num_iters):
        dj_dw, dj_db = compute_gradient(X, y, w, b)
        w -= alpha * dj_dw
        b -= alpha * dj_db
    return w, b

In [24]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>

In [ ]:
# initialize parameters
initial_w = np.zeros_like(w_init)
initial_b = 0.
# some gradient descent settings
iterations = 50000      # as the number of iterations increases, the cost decrease. One major disadvantgae while comparing to sklearn.
alpha = 0.0001
w_final, b_final = multipleLinearRegression(X_train.values, y_train.values, initial_w, initial_b, alpha, iterations)
print(f"w_final: {w_final}, b_final: {b_final}")
print(f"Cost at w_final: {compute_cost(X_train.values, y_train.values, w_final, b_final):.4f}")

y_pred = predict(X_test.values, w_final, b_final)
mse = np.mean((y_pred -  y_test.values) ** 2)
rmse = math.sqrt(mse)
print(f"MSE: {mse:.4f}, RMSE: {rmse:.4f}")

w_final: [ 2.28218428  0.83864612 -1.28409252 -0.22492737], b_final: -4.164094346125552
Cost at w_final: 13.5206
MSE: 28.7299, RMSE: 5.3600

In [22]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred_sklearn = model.predict(X_test)
mse = np.mean((y_pred_sklearn -  y_test.values) ** 2)
rmse = math.sqrt(mse)
print(f"MSE: {mse:.4f}, RMSE: {rmse:.4f}")

MSE: 4.1823, RMSE: 2.0451